development:
  SECRET_KEY: superdevelopmentsecretkey
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST: 127.0.0.1
      PORT: 5432
      NAME: main
      USER: postgres
      PASSWORD: fLlE9Oa6wFMpmMNr

production:
  SECRET_KEY: 8r7ds89fUhfiods@%fjiodsklFnnkdsfjdszxzETZJ*#()09534*Dnfsjkfnsdjkn
  DEBUG: false
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      HOST: 127.0.0.1
      PORT: 5432
      NAME: main
      USER: postgres
      PASSWORD: fLlE9Oa6wFMpmMNr
