development:
  SECRET_KEY: superdevelopmentsecretkey
  # DATABASES:
  #   default:
  #     ENGINE: django.db.backends.postgresql
  #     HOST: 127.0.0.1
  #     PORT: 5432
  #     NAME: main
  #     USER: postgres
  #     PASSWORD: fLlE9Oa6wFMpmMNr

production:
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
